### ISSUE TITLE
Not support BCC, CC and others

### ISSUE THREAD

**Issue by OzzyCzech** [michael-kuk/NetteMailgun#1]
Hi,

see https://documentation.mailgun.com/api-sending.html#sending and `POST /<domain>/messages.mime`

Mailgun do not support BCC and CC just TO and message.

**Comment by michael-kuk** [comment]
Hi, thanks for pointing this out to me, I shall fix it. :)

**Comment by OzzyCzech** [comment]
We have our solution here https://github.com/wikidi/mailgunSender/blob/master/src/MailgunSender.php

But it's waiting for https://github.com/nette/mail/pull/11

**Comment by OzzyCzech** [comment]
I'm closing this issue
